version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./shared:/shared
    working_dir: /app
    command: npm run dev
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
    working_dir: /app
    command: npm start
    restart: unless-stopped